version: '3.7'

services:
  mongo-db:
    container_name: mongoDB
    image: mongo:latest
    restart: always
    volumes:
      - ./nodeTs:/data/db
    environment:
      - MONGO_INITDB_DATABASE= NodeTs
    ports:
      - 27017:27017
